In [2]:
from pathlib import Path

import pandas as pd
import numpy as np

DATA_PATH = Path("../data/raw/online_retail_II.xlsx")

if not DATA_PATH.exists():
    raise FileNotFoundError(f"Data file not found at {DATA_PATH}. Please ensure the file exists.")

print("Pandas version:", pd.__version__)
print("NumPy version:", np.__version__)
print("File location:", DATA_PATH.resolve())
print(f"File size: {DATA_PATH.stat().st_size / (1024**2):.2f} MB")

Pandas version: 3.0.6
NumPy version: 2.4.6
File location: C:\Users\SAMSUNG\OneDrive\Desktop\PythonProjects\retail-pulse-analytics\data\raw\online_retail_II.xlsx
File size: 43.51 MB

In [3]:
with pd.ExcelFile(DATA_PATH, engine="openpyxl") as workbook:
    sheet_names = workbook.sheet_names

print("Sheet names:", sheet_names)

Sheet names: ['Year 2009-2010', 'Year 2010-2011']

In [4]:
df = pd.read_excel(DATA_PATH, sheet_name=sheet_names[0], engine="openpyxl")

print("Loaded worksheet:", sheet_names[0])
print("DataFrame shape:", df.shape)

Loaded worksheet: Year 2009-2010
DataFrame shape: (525461, 8)

In [5]:
df = pd.read_excel(
    DATA_PATH,
    sheet_name=None,
    engine="openpyxl"
)

df = pd.concat(
    df.values(),
    ignore_index=True
)

print("Combined dataset shape:", df.shape)

Combined dataset shape: (1067371, 8)

In [6]:
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])
print("Shape:", df.shape)

Number of rows: 1067371
Number of columns: 8
Shape: (1067371, 8)

In [7]:
print(df.columns.tolist())

['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'Price', 'Customer ID', 'Country']

In [8]:
display(df.head())

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [9]:
display(df.sample(n=5, random_state=42))

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
455941,532657,21314,SMALL GLASS HEART TRINKET POT,12,2010-11-14 11:10:00,2.10,14562.0,United Kingdom
826291,563214,22383,LUNCH BAG SUKI DESIGN,2,2011-08-14 12:56:00,1.65,16370.0,United Kingdom
191636,507597,22561,WOODEN SCHOOL COLOURING SET,12,2010-05-10 13:21:00,1.65,17700.0,United Kingdom
25864,491634,21588,RETRO SPOT GIANT TUBE MATCHES,1,2009-12-11 15:40:00,2.55,17841.0,United Kingdom
73233,496007,85232B,SET/3 RUSSIAN DOLL STACKING TINS,3,2010-01-28 12:32:00,4.95,15203.0,United Kingdom

In [10]:
df.info(memory_usage="deep")

<class 'pandas.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  object
 1   StockCode    1067371 non-null  object
 2   Description  1062989 non-null  object
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  datetime64[us]
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 266.5 MB

In [14]:
missing_counts = df.isna().sum()

display(
    missing_counts.sort_values(ascending=False)
)

Customer ID    243007
Description      4382
StockCode           0
Invoice             0
Quantity            0
InvoiceDate         0
Price               0
Country             0
dtype: int64

In [17]:
missing_percentage = (
    df.isna().mean().mul(100).round(2)
)
display(
    missing_percentage.sort_values(ascending=False)
)

Customer ID    22.77
Description     0.41
StockCode       0.00
Invoice         0.00
Quantity        0.00
InvoiceDate     0.00
Price           0.00
Country         0.00
dtype: float64

In [19]:
print(df.isna().sum())

Invoice             0
StockCode           0
Description      4382
Quantity            0
InvoiceDate         0
Price               0
Customer ID    243007
Country             0
dtype: int64

In [21]:
df.info(memory_usage="deep")

<class 'pandas.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  object
 1   StockCode    1067371 non-null  object
 2   Description  1062989 non-null  object
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  datetime64[us]
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 266.5 MB